-- 初始化数据库表结构

-- 报价单表
CREATE TABLE IF NOT EXISTS quotation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL COMMENT '商品 ID',
    seller_id BIGINT NOT NULL COMMENT '卖方 ID',
    buyer_id BIGINT NOT NULL COMMENT '买方 ID',
    original_price DECIMAL(10,2) NOT NULL COMMENT '原价',
    quoted_price DECIMAL(10,2) NOT NULL COMMENT '报价',
    status VARCHAR(20) NOT NULL DEFAULT 'INITIATED' COMMENT '状态：INITIATED, COUNTERED, ACCEPTED, REJECTED, EXPIRED',
    version INT NOT NULL DEFAULT 1 COMMENT '乐观锁版本号',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    expired_at TIMESTAMP NOT NULL COMMENT '过期时间'
);

-- 商品库存表
CREATE TABLE IF NOT EXISTS product_inventory (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL UNIQUE COMMENT '商品 ID',
    stock_quantity INT NOT NULL DEFAULT 0 COMMENT '库存数量',
    unit_price DECIMAL(10,2) NOT NULL COMMENT '单价',
    version INT NOT NULL DEFAULT 1 COMMENT '乐观锁版本号',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);

-- 插入测试数据
INSERT INTO product_inventory (product_id, stock_quantity, unit_price) VALUES 
(1001, 100, 99.99),
(1002, 50, 199.99),
(1003, 200, 49.99);
