CREATE TABLE IF NOT EXISTS quotation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL COMMENT '商品ID',
    product_name VARCHAR(255) NOT NULL COMMENT '商品名称',
    original_price DECIMAL(10,2) NOT NULL COMMENT '原始价格',
    current_price DECIMAL(10,2) NOT NULL COMMENT '当前报价',
    min_acceptable_price DECIMAL(10,2) NOT NULL COMMENT '最低可接受价格',
    stock_quantity INT NOT NULL DEFAULT 0 COMMENT '库存数量',
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING, COUNTER_OFFER, ACCEPTED, REJECTED',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号（乐观锁）',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    INDEX idx_product_id (product_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价单表';
